# OpenCV에서 제공하는 사칙연산 함수

- cv2.add(src1, src2, dest, mask, dtype)
    - src1, src2 : 입력이미지1, 입력이미지2
    - dest(optional) : 출력 영상
    - mask(optional) : mask값이 0이 아닌 픽셀만 연산
    - dtype(optional) : Output dtype
  
  
  
- cv2.subtract(src1, src2, dest, mask, dtype)
    빼기 연산, 나머지는 위와 동일



- cv2.multiply(src1, src2, dest, scale, dtype)
    곱하기 연산, 나머지는 위와 동일
    - scale(optional) : 연산 결과에 추가 연산할 값



- cv2.divide(src1, src2, scale, dtype)
    나누기 연산


In [2]:
import cv2
import numpy as np

a = np.uint8([[200, 50]])
b = np.uint8([[100, 100]])

add1 = a + b
sub1 = a - b
multi1 = a * 2
div1 = a / 3

add2 = cv2.add(a, b)
sub2 = cv2.subtract(a, b)
mult2 = cv2.multiply(a , 2)
div2 = cv2.divide(a, 3)

print(add1, add2)
print(sub1, sub2)
print(multi1, mult2)
print(div1, div2)

[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]


### numpy 연산 결과와 OpenCV 연산 결과가 서로 다르다

### uint8 dtype은 0 ~ 255 범위이므로 255를 넘기면 다시 0부터 카운팅을 한다.
### cv2는 255를 넘기면 모두 255로 반환한다.
### cv2에서는 0보다 작은 값은 0으로 반환한다.